apiVersion: apps/v1
kind: Deployment
metadata:
  name: san-express-app
  labels:
    app: san-express-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: san-express-app
  template:
    metadata:
      labels:
        app: san-express-app
    spec:
      containers:
        - name: san-express-app
          image: 'sandydevops8/san-express-app:${GIT_SHA}'   # Use your actual app image here
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
